import hljs from 'highlight.js/lib/core';

import accesslog  from 'highlight.js/lib/languages/accesslog';
import apache     from 'highlight.js/lib/languages/apache';
import arduino    from 'highlight.js/lib/languages/arduino';
import asciidoc   from 'highlight.js/lib/languages/asciidoc';
import bash       from 'highlight.js/lib/languages/bash';
import c          from 'highlight.js/lib/languages/c';
import cmake      from 'highlight.js/lib/languages/cmake';
import cpp        from 'highlight.js/lib/languages/cpp';
import csharp     from 'highlight.js/lib/languages/csharp';
import css        from 'highlight.js/lib/languages/css';
import dart       from 'highlight.js/lib/languages/dart';
import diff       from 'highlight.js/lib/languages/diff';
import dockerfile from 'highlight.js/lib/languages/dockerfile';
import dos        from 'highlight.js/lib/languages/dos';
import graphql    from 'highlight.js/lib/languages/graphql';
import http       from 'highlight.js/lib/languages/http';
import ini        from 'highlight.js/lib/languages/ini';
import java       from 'highlight.js/lib/languages/java';
import javascript from 'highlight.js/lib/languages/javascript';
import json       from 'highlight.js/lib/languages/json';
import lua        from 'highlight.js/lib/languages/lua';
import makefile   from 'highlight.js/lib/languages/makefile';
import markdown   from 'highlight.js/lib/languages/markdown';
import nginx      from 'highlight.js/lib/languages/nginx';
import perl       from 'highlight.js/lib/languages/perl';
import php        from 'highlight.js/lib/languages/php';
import plaintext  from 'highlight.js/lib/languages/plaintext';
import powershell from 'highlight.js/lib/languages/powershell';
import processing from 'highlight.js/lib/languages/processing';
import protobuf   from 'highlight.js/lib/languages/protobuf';
import python     from 'highlight.js/lib/languages/python';
import scss       from 'highlight.js/lib/languages/scss';
import shell      from 'highlight.js/lib/languages/shell';
import sql        from 'highlight.js/lib/languages/sql';
import typescript from 'highlight.js/lib/languages/typescript';
import vbscript   from 'highlight.js/lib/languages/vbscript';
import wasm       from 'highlight.js/lib/languages/wasm';
import xml        from 'highlight.js/lib/languages/xml';
import xquery     from 'highlight.js/lib/languages/xquery';
import yaml       from 'highlight.js/lib/languages/yaml';

hljs.registerLanguage('accesslog',  accesslog);
hljs.registerLanguage('apache',     apache);
hljs.registerLanguage('arduino',    arduino);
hljs.registerLanguage('asciidoc',   asciidoc);
hljs.registerLanguage('bash',       bash);
hljs.registerLanguage('c',          c);
hljs.registerLanguage('cmake',      cmake);
hljs.registerLanguage('cpp',        cpp);
hljs.registerLanguage('csharp',     csharp);
hljs.registerLanguage('css',        css);
hljs.registerLanguage('dart',       dart);
hljs.registerLanguage('diff',       diff);
hljs.registerLanguage('dockerfile', dockerfile);
hljs.registerLanguage('dos',        dos);
hljs.registerLanguage('graphql',    graphql);
hljs.registerLanguage('http',       http);
hljs.registerLanguage('ini',        ini);
hljs.registerLanguage('java',       java);
hljs.registerLanguage('javascript', javascript);
hljs.registerLanguage('json',       json);
hljs.registerLanguage('lua',        lua);
hljs.registerLanguage('makefile',   makefile);
hljs.registerLanguage('markdown',   markdown);
hljs.registerLanguage('nginx',      nginx);
hljs.registerLanguage('perl',       perl);
hljs.registerLanguage('php',        php);
hljs.registerLanguage('plaintext',  plaintext);
hljs.registerLanguage('powershell', powershell);
hljs.registerLanguage('processing', processing);
hljs.registerLanguage('protobuf',   protobuf);
hljs.registerLanguage('python',     python);
hljs.registerLanguage('scss',       scss);
hljs.registerLanguage('shell',      shell);
hljs.registerLanguage('sql',        sql);
hljs.registerLanguage('typescript', typescript);
hljs.registerLanguage('vbscript',   vbscript);
hljs.registerLanguage('wasm',       wasm);
hljs.registerLanguage('xml',        xml);
hljs.registerLanguage('xquery',     xquery);
hljs.registerLanguage('yaml',       yaml);

window.hljs = hljs;